
const entries = [];
const US_STATES = ["AL","AK","AS","AZ","AR","CA","CO","CT","DE","DC","FL","GA","GU","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","MP","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","PR","RI","SC","SD","TN","TX","VI","UT","VT","VA","WA","WV","WI","WY"];

function el(tag, attrs={}, children=[]) { const e=document.createElement(tag); Object.entries(attrs).forEach(([k,v])=>{ if(k==='class') e.className=v; else if(k==='dataset') Object.entries(v).forEach(([dk,dv])=> e.dataset[dk]=dv); else if(k.startsWith('on')&&typeof v==='function') e.addEventListener(k.substring(2), v); else e.setAttribute(k,v); }); (Array.isArray(children)?children:[children]).forEach(c=>{ if(c==null) return; e.appendChild(typeof c==='string'?document.createTextNode(c):c); }); return e; }

function enforceCheckboxLimit(w){ const l=parseInt(w.dataset.limit||'0',10); if(!l) return; const c=w.querySelectorAll('input[type="checkbox"]'); c.forEach(cb=>cb.addEventListener('change',()=>{ const ch=[...c].filter(x=>x.checked); if(ch.length>l){ cb.checked=false; alert(`You can select up to ${l} options.`); } })); }

function wireForm(id){ const f=document.getElementById(id); if(!f) return; f.querySelectorAll('[data-limit]').forEach(enforceCheckboxLimit); f.addEventListener('submit',e=>{ e.preventDefault(); const fd=new FormData(f); const obj={}; for(const [k,v] of fd.entries()){ if(obj[k]!==undefined){ if(Array.isArray(obj[k])) obj[k].push(String(v)); else obj[k]=[String(obj[k]),String(v)]; } else obj[k]=String(v); } const formName=f.dataset.formName; const timestamp=new Date().toISOString(); entries.push({form:formName,data:obj,timestamp}); renderTable(); f.reset(); }); }

function renderTable(){ const out=document.getElementById('outputTableBody'); const head=document.getElementById('outputTableHead'); out.innerHTML=''; const keys=new Set(['Form','Timestamp']); entries.forEach(e=>Object.keys(e.data).forEach(k=>keys.add(k))); head.innerHTML=''; Array.from(keys).forEach(k=> head.appendChild(el('th',{},k))); entries.forEach((entry,idx)=>{ const tr=el('tr'); const row=Object.assign({Form:entry.form,Timestamp:entry.timestamp}, entry.data); Array.from(keys).forEach(k=> tr.appendChild(el('td',{}, row[k]!==undefined ? (Array.isArray(row[k])?row[k].join(', '):row[k]) : ''))); const act=el('td',{}, [ el('button',{class:'ghost',onclick:()=>editEntry(idx)},'Edit'), el('button',{class:'ghost',onclick:()=>deleteEntry(idx)},'Delete') ]); tr.appendChild(act); out.appendChild(tr); }); head.appendChild(el('th',{},'Actions')); }

function editEntry(i){ const e=entries[i]; if(!e) return; const s=document.getElementById('formSelector'); s.value=e.form; activateForm(e.form); const f=document.querySelector(`[data-form-name="${e.form}"]`); if(!f) return; f.reset(); Object.entries(e.data).forEach(([k,v])=>{ const els=f.querySelectorAll(`[name="${k}"]`); els.forEach(elm=>{ if(elm.type==='checkbox'||elm.type==='radio'){ if(Array.isArray(v)) elm.checked=v.includes(elm.value); else elm.checked=(String(v)===elm.value); } else { elm.value=Array.isArray(v)?v[0]:v; } }); }); entries.splice(i,1); renderTable(); }

function deleteEntry(i){ entries.splice(i,1); renderTable(); }

function exportExcel(){ if(entries.length===0){ alert('No entries to export.'); return; } const keys=new Set(['Form','Timestamp']); entries.forEach(e=>Object.keys(e.data).forEach(k=>keys.add(k))); const keyList=Array.from(keys); const rows=[keyList]; entries.forEach(e=>{ const row=Object.assign({Form:e.form,Timestamp:e.timestamp}, e.data); rows.push(keyList.map(k=>{ const v=row[k]; return Array.isArray(v)?v.join(', '):(v===undefined?'':String(v)); })); }); const wb=XLSX.utils.book_new(); const ws=XLSX.utils.aoa_to_sheet(rows); Object.keys(ws).forEach(addr=>{ if(!/^!/.test(addr)) ws[addr].t='s'; }); XLSX.utils.book_append_sheet(wb, ws, 'Entries'); XLSX.writeFile(wb, 'Survey_Entries.xlsx'); }

function activateForm(n){ document.querySelectorAll('.form-wrapper').forEach(w=>w.classList.add('hidden')); const a=document.getElementById('form_'+n.replace(/\W+/g,'_')); if(a)a.classList.remove('hidden'); }

document.addEventListener('DOMContentLoaded',()=>{ document.querySelectorAll('form[data-form-name]').forEach(f=>wireForm(f.id)); const sel=document.getElementById('formSelector'); if(sel) sel.addEventListener('change', e=>activateForm(e.target.value)); const dl=document.getElementById('downloadExcel'); if(dl) dl.addEventListener('click', exportExcel); });
